server:
  context-path: /uaa
  port: 5000

management:
  security:
    enabled: false
  context-path: /mgmt
#注册中心
eureka:
  instance:
    health-check-url-path: ${server.context-path}${management.context-path}/health
    status-page-url-path: ${server.context-path}${management.context-path}/info
    metadata-map:
      management.context-path: ${server.context-path}${management.context-path}
#安全配置
security:
  ignored: /css/**,/js/**,/images/**,/webjars/**,/**/favicon.ico,/static/**,/api/swagger-ui.html,/swagger-ui.html,/v2/api-docs, /configuration/ui,/swagger-resources
#数据源配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jiajiaozaixian_dev?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: jiuaiNI0523
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  jpa:
    show-sql: true
#swagger接口配置
swagger:
  base-package: com.ailikes.auth
