server:
  host: 127.0.0.1
  port: 5000
  context-path: /uaa
var:
  env: dev
  name: auth-service
  msg: This service AUTH-SERVICE in dev
management:
  security:
    enabled: false
  context-path: /mgmt
#注册中心
eureka:
  instance:
    health-check-url-path: ${server.context-path}${management.context-path}/health
    status-page-url-path: ${server.context-path}${management.context-path}/info
    metadata-map:
      management.context-path: ${server.context-path}${management.context-path}
#安全配置
  security:
    ignored: /css/**,/js/**,/images/**,/webjars/**,/**/favicon.ico,/static/**,/public/**,/api/swagger-ui.html,/swagger-ui.html,/v2/api-docs, /configuration/ui,/swagger-resources
#数据源配置
spring:
  datasource:
    url: jdbc:mysql://111.207.248.45:3306/jiajiaozaixian_dev?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: jiuaiNI0523
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  jpa:
    show-sql: true
# thymeleaf:
#   prefix: classpath:/templates/
  freemarker: 
    suffix: .html # 设置模板后缀名 
    content-type: text/html # 设置文档类型 
    charset: UTF-8                               # 设置页面编码格式 
    cache: false                                 # 设置页面缓存 
    template-loader-path: classpath:/templates # 设置ftl文件路径 
    mvc: 
      static-path-pattern: /static # 设置静态文件路径，js,css等

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/jjzx/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package:  com.ailikes.jjzx.entity
  #typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  configuration-properties:
    dbType: mysql #设置全局属性用于控制数据库的类型

#swagger接口配置
swagger:
  base-package: com.ailikes.auth

