server:
  port: 8761
#注册中心配置
eureka:
  instance:
    hostname: registry.junxinweike.club
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
#安全
security:
  user:
    name: user
    password: ${REGISTRY_SERVER_PASSWORD:password}
